public class BarChartBarData{
    
    public String label;
    public String subLabel;
    public Double value;
    public String color;
    public String info;
    public String extra;
    
    public BarChartBarData(String label, String subLabel, Double value, String color){
        
        this.label = label;
        this.subLabel = subLabel;
        this.value = value;
        this.color = color;
        
    }
    
}