public class AppInfoData {
    
    public String id;
    public String name;
    public String version;
    public String appleStoreUrl;
    public String googlePlayStoreUrl;
    public String iosVersion;
    public String androidVersion;
    public String privacyIt;
    public String privacyEn;
    public String descriptionIt;
    public String descriptionEn;
    public String phoneContact;
    public String emailContact;
    public Map<String, Object> configurations;
    
    public AppInfoData(){
        
    }

}